apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: demo
    image: docker.io/rkalluru/learnk8s:rhel9-bare
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"

# Values in k8s if it is string, then quotes are nto mandatory. but if it is a integer then it is must.


